In [2]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv


# import libraries

In [1]:
import numpy as np
import pandas as pd

In [3]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [4]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [5]:

for array in [
    np.array([1,2,3,4,5]),
    np.array([[5,6,7],[9,0,1]]),
    np.array([[[10,20,30],[60,40,70]], [[90, 120, 45],[77,29,83]]]),
    np.array([
        [[[66,74,22],[53,90,18]], [[34,56,11],[100,77,99]]],
        [[[88,300,66],[35,46,29]], [[76,42,59],[47,13,46]]]
    ])
]:
    
    print(f"{array.ndim}D Array: \n {array}")
    print("")
    print(f"Dimension of {array.ndim}D Array", np.ndim(array),"\n")

1D Array: 
 [1 2 3 4 5]

Dimension of 1D Array 1 

2D Array: 
 [[5 6 7]
 [9 0 1]]

Dimension of 2D Array 2 

3D Array: 
 [[[ 10  20  30]
  [ 60  40  70]]

 [[ 90 120  45]
  [ 77  29  83]]]

Dimension of 3D Array 3 

4D Array: 
 [[[[ 66  74  22]
   [ 53  90  18]]

  [[ 34  56  11]
   [100  77  99]]]


 [[[ 88 300  66]
   [ 35  46  29]]

  [[ 76  42  59]
   [ 47  13  46]]]]

Dimension of 4D Array 4 



# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [21]:
arr_1d= np.arange(7)
print("1D Array:\n",arr_1d)
print("Dimension of 1D array:",np.ndim(arr_1d))

arr_2d = np.arange(6).reshape(2, 3)
print("\n2D Array:")
print(arr_2d)
print("Dimension of 2D array:",np.ndim(arr_2d))

arr_3d = np.arange(12).reshape(2, 2, 3)
print("\n3D Array:")
print(arr_3d)
print("Dimension of 3D array:",np.ndim(arr_3d))

arr_4d = np.arange(16).reshape(2, 2, 2, 2)
print("\n4D Array:")
print(arr_4d)
print("Dimension of 4D array:",np.ndim(arr_4d))

1D Array:
 [0 1 2 3 4 5 6]
Dimension of 1D array: 1

2D Array:
[[0 1 2]
 [3 4 5]]
Dimension of 2D array: 2

3D Array:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Dimension of 3D array: 3

4D Array:
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
Dimension of 4D array: 4


# create array using ones and zeros

In [31]:
ones_matrix= np.ones((3,3))
print("Ones Matrix:\n", ones_matrix,"\n")
zero_matrix= np.zeros((3,4))
print("Zero Matrix:\n",zero_matrix)

Ones Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

Zero Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# using random

In [57]:
a1= np.random.random(5)
print("1D Array usnig random: \n", a1)
a2= np.random.random((2,3))
print("\n2D Array using random:\n", a2)
a3= np.random.random((2,3,4))
print("\n3D Array using random:\n", a3)
a4= np.random.random((2,3,4,5))
print("\n4D Array using random:\n", a4)

1D Array usnig random: 
 [0.56884467 0.95063194 0.25153308 0.91203499 0.2528584 ]

2D Array using random:
 [[0.3421483  0.02555992 0.44205743]
 [0.36684074 0.76416081 0.5658694 ]]

3D Array using random:
 [[[0.04655282 0.79115689 0.45422242 0.26999441]
  [0.31092016 0.66626008 0.493066   0.57798963]
  [0.92145114 0.73952806 0.37766813 0.73623508]]

 [[0.99677674 0.1304601  0.5396065  0.29807828]
  [0.45209345 0.0933148  0.20210529 0.67147424]
  [0.40157615 0.11037896 0.32540335 0.18774713]]]

4D Array using random:
 [[[[0.22443051 0.1178783  0.9350079  0.31524813 0.64815443]
   [0.91618752 0.0832027  0.0448604  0.82087285 0.4454751 ]
   [0.97843657 0.50812611 0.14898856 0.24250882 0.29156438]
   [0.3299034  0.13770996 0.75053335 0.36944885 0.56889329]]

  [[0.86554616 0.89325714 0.9145069  0.1646448  0.82243456]
   [0.23415926 0.35601348 0.01626469 0.23829141 0.28965895]
   [0.98445521 0.19446829 0.36303379 0.1503508  0.88496878]
   [0.59388144 0.01540977 0.17670177 0.89016018 0.212302

# using linspace

In [59]:
np.linspace(15,95,17, dtype=int)

array([15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

# create 1D array of tip from tips dataframe

In [73]:
tips.head()
tip_data= tips["tip"].to_numpy()
tip_data

array([ 1.01,  1.66,  3.5 ,  3.31,  3.61,  4.71,  2.  ,  3.12,  1.96,
        3.23,  1.71,  5.  ,  1.57,  3.  ,  3.02,  3.92,  1.67,  3.71,
        3.5 ,  3.35,  4.08,  2.75,  2.23,  7.58,  3.18,  2.34,  2.  ,
        2.  ,  4.3 ,  3.  ,  1.45,  2.5 ,  3.  ,  2.45,  3.27,  3.6 ,
        2.  ,  3.07,  2.31,  5.  ,  2.24,  2.54,  3.06,  1.32,  5.6 ,
        3.  ,  5.  ,  6.  ,  2.05,  3.  ,  2.5 ,  2.6 ,  5.2 ,  1.56,
        4.34,  3.51,  3.  ,  1.5 ,  1.76,  6.73,  3.21,  2.  ,  1.98,
        3.76,  2.64,  3.15,  2.47,  1.  ,  2.01,  2.09,  1.97,  3.  ,
        3.14,  5.  ,  2.2 ,  1.25,  3.08,  4.  ,  3.  ,  2.71,  3.  ,
        3.4 ,  1.83,  5.  ,  2.03,  5.17,  2.  ,  4.  ,  5.85,  3.  ,
        3.  ,  3.5 ,  1.  ,  4.3 ,  3.25,  4.73,  4.  ,  1.5 ,  3.  ,
        1.5 ,  2.5 ,  3.  ,  2.5 ,  3.48,  4.08,  1.64,  4.06,  4.29,
        3.76,  4.  ,  3.  ,  1.  ,  4.  ,  2.55,  4.  ,  3.5 ,  5.07,
        1.5 ,  1.8 ,  2.92,  2.31,  1.68,  2.5 ,  2.  ,  2.52,  4.2 ,
        1.48,  2.  ,

# create 2D array of tip and total_bill form tips dataframe

In [85]:
tips.head()
tips[["total_bill","tip"]].to_numpy()

array([[16.99,  1.01],
       [10.34,  1.66],
       [21.01,  3.5 ],
       [23.68,  3.31],
       [24.59,  3.61],
       [25.29,  4.71],
       [ 8.77,  2.  ],
       [26.88,  3.12],
       [15.04,  1.96],
       [14.78,  3.23],
       [10.27,  1.71],
       [35.26,  5.  ],
       [15.42,  1.57],
       [18.43,  3.  ],
       [14.83,  3.02],
       [21.58,  3.92],
       [10.33,  1.67],
       [16.29,  3.71],
       [16.97,  3.5 ],
       [20.65,  3.35],
       [17.92,  4.08],
       [20.29,  2.75],
       [15.77,  2.23],
       [39.42,  7.58],
       [19.82,  3.18],
       [17.81,  2.34],
       [13.37,  2.  ],
       [12.69,  2.  ],
       [21.7 ,  4.3 ],
       [19.65,  3.  ],
       [ 9.55,  1.45],
       [18.35,  2.5 ],
       [15.06,  3.  ],
       [20.69,  2.45],
       [17.78,  3.27],
       [24.06,  3.6 ],
       [16.31,  2.  ],
       [16.93,  3.07],
       [18.69,  2.31],
       [31.27,  5.  ],
       [16.04,  2.24],
       [17.46,  2.54],
       [13.94,  3.06],
       [ 9.

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [90]:
print("Here 4 Examples of 1D, 2D, 3D, 4D Arrays\n")

print("Example -- 1 \n")
array1 = np.array([10, 20, 30, 40, 50])
print("Array:", array1)
print("ndim:", array1.ndim)     
print("shape:", array1.shape)
print("size:", array1.size)     
print("itemsize:", array1.itemsize)

print("\nExample -- 2 \n")
array2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray:", array2)
print("ndim:", array2.ndim)
print("shape:", array2.shape)
print("size:", array2.size)
print("itemsize:", array2.itemsize)

print("\nExample -- 3 \n")
arr3 = np.arange(12).reshape(2, 2, 3)
print("3D Array:")
print(arr3)
print("ndim:", arr3.ndim)
print("shape:", arr3.shape)
print("size:", arr3.size)
print("itemsize:", arr3.itemsize)

print("\nExample -- 4 \n")
arr4 = np.arange(16).reshape(2, 2, 2, 2)
print("\n4D Array:")
print(arr4)
print("ndim:", arr4.ndim)
print("shape:", arr4.shape)
print("size:", arr4.size)
print("itemsize:", arr4.itemsize)

Here 4 Examples of 1D, 2D, 3D, 4D Arrays

Example -- 1 

Array: [10 20 30 40 50]
ndim: 1
shape: (5,)
size: 5
itemsize: 8

Example -- 2 


Array: [[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
size: 6
itemsize: 8

Example -- 3 

3D Array:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
ndim: 3
shape: (2, 2, 3)
size: 12
itemsize: 8

Example -- 4 


4D Array:
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
ndim: 4
shape: (2, 2, 2, 2)
size: 16
itemsize: 8


# change data type and memory size of any np-array using astype()

In [98]:
ar1= np.array([10, 20, 30, 40, 50])
print("Before:")
print("Array:",ar1)
print("Data type:", ar1.dtype)
print("Memory size:", ar1.itemsize, "bytes")

ar1_new= ar1.astype(np.int32)
print("\nAfter:")
print(ar1_new)
print("Data type:", ar1_new.dtype)
print("Memory size:", ar1_new.itemsize, "bytes")

Before:
Array: [10 20 30 40 50]
Data type: int64
Memory size: 8 bytes

After:
[10 20 30 40 50]
Data type: int32
Memory size: 4 bytes


# create 2 same dimensional array and do scalar and vector operations

In [116]:
x= np.arange(12).reshape(3,4)
y= np.arange(13,25).reshape(3,4)

print("Scalar Operations\n")
print("x**3 =\n", x**3)

print("\nVector Operations\n")
print("x+y =\n", x+y)

Scalar Operations

x**3 =
 [[   0    1    8   27]
 [  64  125  216  343]
 [ 512  729 1000 1331]]

Vector Operations

x+y =
 [[13 15 17 19]
 [21 23 25 27]
 [29 31 33 35]]



# find minimun and maximum tip

In [124]:
value= tips["tip"]
print("Minimum value from tip: ",np.min(value))
print("Maximum value from tip: ",np.max(value))

Minimum value from tip:  1.0
Maximum value from tip:  10.0


# find average total_bill and average tip

In [131]:
total_bill= tips["total_bill"]
tip= tips["tip"]
print("Average total bill: ",np.mean(total_bill))
print("Average tip: ",np.mean(tip))

Average total bill:  19.78594262295082
Average tip:  2.99827868852459


# find median total_bill

In [136]:
print("Median of total bill: ",np.median(tips["total_bill"]))

Median of total bill:  17.795


# find standard deviasion and variance of tip

In [142]:
print("Standard Deviasion of tip: ",np.std(tips["tip"]))
print("Varience of tip: ",np.var(tips["tip"]))

Standard Deviasion of tip:  1.3807999538298958
Varience of tip:  1.9066085124966428


# find log values of tip

In [146]:
find_log= tips["tip"]
print("Find log values of tip: \n",np.log(find_log))

Find log values of tip: 
 0      0.009950
1      0.506818
2      1.252763
3      1.196948
4      1.283708
         ...   
239    1.778336
240    0.693147
241    0.693147
242    0.559616
243    1.098612
Name: tip, Length: 244, dtype: float64


# apply round, floor and ceil operation on tip array

In [153]:
print("1. Floor Operation on tip array: \n",np.floor(tips["tip"]))
print("\n2. Ceil Operation on tip array: \n",np.ceil(tips["tip"]))
print("\n3. Round Operation on tip array: \n",np.round(tips["tip"]))

1. Floor Operation on tip array: 
 0      1.0
1      1.0
2      3.0
3      3.0
4      3.0
      ... 
239    5.0
240    2.0
241    2.0
242    1.0
243    3.0
Name: tip, Length: 244, dtype: float64

2. Ceil Operation on tip array: 
 0      2.0
1      2.0
2      4.0
3      4.0
4      4.0
      ... 
239    6.0
240    2.0
241    2.0
242    2.0
243    3.0
Name: tip, Length: 244, dtype: float64

3. Round Operation on tip array: 
 0      1.0
1      2.0
2      4.0
3      3.0
4      4.0
      ... 
239    6.0
240    2.0
241    2.0
242    2.0
243    3.0
Name: tip, Length: 244, dtype: float64


# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [163]:
# For 1D Array
arr1 = np.array([10, 20, 30, 40, 50, 60, 70])
#indexing
print("1D Array:", arr1)
print("First element: ",arr1[0])     
print("Third element :",arr1[2])      
print("Last element :",arr1[-1])    
print("Second last element :",arr1[-2])    
print("Fourth element :",arr1[3]) 
#Slicing
print("First three elements :",arr1[0:3])    
print("Elements from index 2 to 5 :",arr1[2:6])     
print("From beginning to index 3 :",arr1[:4])     
print("From index 3 to end :",arr1[3:])      
print("Every second element :",arr1[::2])    

# For 2D Array
arr2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
#indexing
print("\n2D Array:\n", arr2)
print("First element: ", arr2[0, 0])
print("Second row, third element: ", arr2[1, 2])
print("Last element: ", arr2[-1, -1])
print("Second row, first element: ", arr2[1, 0])
print("Third row, second element: ", arr2[2, 1])
# slicing
print("First two rows:\n", arr2[0:2, :])
print("First two columns:\n", arr2[:, 0:2])
print("First two rows and first three columns:\n", arr2[0:2, 0:3])
print("From second row to end:\n", arr2[1:, :])
print("Every second column:\n", arr2[:, ::2])

# For 3D Array
arr3 = np.array([
    [
        [10, 20, 30],
        [40, 50, 60]
    ],
    [
        [70, 80, 90],
        [100, 110, 120]
    ]
])
# indexing
print("\n3D Array:\n", arr3)
print("First element: ", arr3[0, 0, 0])
print("First block, second row, third element: ", arr3[0, 1, 2])
print("Second block, first row, second element: ", arr3[1, 0, 1])
print("Second block, second row, first element: ", arr3[1, 1, 0])
print("Last element: ", arr3[-1, -1, -1])
# slicing
print("First block:\n", arr3[0, :, :])
print("Second block:\n", arr3[1, :, :])
print("First row from all blocks:\n", arr3[:, 0, :])
print("First two columns from all blocks:\n", arr3[:, :, 0:2])
print("Every second column:\n", arr3[:, :, ::2])

1D Array: [10 20 30 40 50 60 70]
First element:  10
Third element : 30
Last element : 70
Second last element : 60
Fourth element : 40
First three elements : [10 20 30]
Elements from index 2 to 5 : [30 40 50 60]
From beginning to index 3 : [10 20 30 40]
From index 3 to end : [40 50 60 70]
Every second element : [10 30 50 70]

2D Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
First element:  10
Second row, third element:  70
Last element:  120
Second row, first element:  50
Third row, second element:  100
First two rows:
 [[10 20 30 40]
 [50 60 70 80]]
First two columns:
 [[ 10  20]
 [ 50  60]
 [ 90 100]]
First two rows and first three columns:
 [[10 20 30]
 [50 60 70]]
From second row to end:
 [[ 50  60  70  80]
 [ 90 100 110 120]]
Every second column:
 [[ 10  30]
 [ 50  70]
 [ 90 110]]

3D Array:
 [[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
First element:  10
First block, second row, third element:  60
Second block, first row, second element: 

# stacking and spliting

In [164]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)

# use hstack() and vstack()

In [171]:
print("hstack: \n",np.hstack((d,e)))
print("\n\n vstack: \n",np.vstack((e,d,e)))

hstack: 
 [[ 0  1  2  3  4  5  6  7  8 28 29 30 31 32 33 34 35 36]
 [ 9 10 11 12 13 14 15 16 17 37 38 39 40 41 42 43 44 45]
 [18 19 20 21 22 23 24 25 26 46 47 48 49 50 51 52 53 54]]


 vstack: 
 [[28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]
 [ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]]


# use hsplit() and vsplit()

In [192]:
print("hsplit & vsplit for 'd' \n")
print("hsplit(d,3) :\n\n", np.hsplit(d, 3))
print("\nvsplit(d,3) :\n\n", np.vsplit(d, 3))
np.vsplit(d,3)

print("\n\nhsplit & vsplit for 'e' \n")

print("hsplit(e,3) :\n\n", np.hsplit(e, 3))
print("\nvsplit(e,3) :\n\n", np.vsplit(e, 3))

hsplit & vsplit for 'd' 

hsplit(d,3) :

 [array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]]), array([[ 3,  4,  5],
       [12, 13, 14],
       [21, 22, 23]]), array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26]])]

vsplit(d,3) :

 [array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]), array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]


hsplit & vsplit for 'e' 

hsplit(e,3) :

 [array([[28, 29, 30],
       [37, 38, 39],
       [46, 47, 48]]), array([[31, 32, 33],
       [40, 41, 42],
       [49, 50, 51]]), array([[34, 35, 36],
       [43, 44, 45],
       [52, 53, 54]])]

vsplit(e,3) :

 [array([[28, 29, 30, 31, 32, 33, 34, 35, 36]]), array([[37, 38, 39, 40, 41, 42, 43, 44, 45]]), array([[46, 47, 48, 49, 50, 51, 52, 53, 54]])]
